server:
  port: 1111

#-------redis相关配置------------------
spring:
  profiles:
    active: dev #表示开发环境
  redis:
    database: 0  #--Redis 数据库索引(默认为 0)
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8  #--连接池最大连接数
        max-wait: -1  #--连接池最大阻塞等待时间(负数表示没有限制) -1
        max-idle: 8  #--最大空闲链接
        min-idle: 0  #--最小空闲连接

