server:
  port: 8001

spring:
  application:
    name: cloud-provider-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver      #mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/springboot_study?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=true
    username: root
    password: zhangtao

eureka:
  client:
    #表示自己注册进eurekaServer默认为true
    register-with-eureka: true
    fetchRegistry: true #是否从eureka抓取自己的注册信息，默认为true,丹姐点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/ #集群版

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.zhangtao.springcloud.entities #所有entity别名类所在包