server:
  port: 8006

spring:
  application:
    name: cloud-provide-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver      #mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/springboot_study?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=true
    username: root
    password: zhangtao
  cloud:                               #consul注册中心配置
    consul:
      host: http://192.168.205.129
      port: 8500
      discovery:
        service-name: ${spring.application.name}

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.zhangtao.springcloud.entities #所有entity别名类所在包
