server:
  port: 84

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.205.129:8848 #配置nacos地址
    sentinel:
      transport: # 配置sentinel dashboard 地址
        dashboard: localhost:8080
        port: 8719 # 默认8719端口，假如被占用从8719开始依次+1扫描 直至找到未被占用的端口

service-url:  # 消费者将要访问的服务名称（nacos注册服务名）
  nacos-user-service: http://nacos-payment-provider

#激活Sentinel对Openfeign的支持   消费端
feign:
  sentinel:
    enabled: true