server:
  port: 8001

spring:
  application:
    name: cloud-provider-hystrix-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver      #mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/springboot_study?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=true
    username: root
    password: zhangtao

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.zhangtao.springcloud.entities #所有entity别名类所在包

eureka:
  client:
    #表示自己注册进eurekaServer默认为true
    register-with-eureka: true
    fetchRegistry: true #是否从eureka抓取自己的注册信息，默认为true,单点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/  #单机版
      #defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/ #集群版
  instance:
    instanceId: payment8001 # 主机名称 eureka注册显示
    prefer-ip-address: true #显示主机IP
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒(默认90s),超时将剔除服务
    #lease-expiration-duration-in-seconds: 2
    #Eureka客户端向服务端发送心跳时间间隔，单位为秒(默认为30s)
    #lease-renewal-interval-in-seconds: 1