server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: #在此处配置要绑定的rabbitmq的服务信息
        defaultRabbit: #表示定义的名称，用于binding整合
          type: rabbit #消息组件类型
          environment: #设置rabbitmq的相关的环境配置
            spring:
              rabbitmq: #rabbitMQ相关配置
                host: 192.168.205.129
                port: 5672 # 15672是Web管理界面的端口；5672是MQ访问的端口
                username: zhang
                password: zhang
                virtual-host: /
      bindings: #服务的整合处理
        input: #消费者 这是一个通道的名称
          destination: studyExchange # 表示要使用 Exchange名称定义
          content-type: application/json #设置消息类型，本次为json, 文本设置为 “text/plain”
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
          #group: zhangA

eureka:
  client:
    register-with-eureka: true #表示自己注册进eurekaServer默认为true
    #fetchRegistry: true #是否从eureka抓取自己的注册信息，默认为true,单点点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
      #defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/ #集群版
  instance:
    lease-expiration-duration-in-seconds: 5 #如果现在超过了5秒的间隔(默认90秒)
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔(默认是30秒)
    instance-id: receive-8802.com #在消息列表时显示主机名称
    prefer-ip-address: true # 访问的路径变为ip地址