server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
       - id: payment_routh  #路由的ID 没有固定的规则 但是要求唯一 建议配服务名
         #uri: http://localhost:8001  #匹配后 提供服务的路由地址
         uri: lb://CLOUD-PROVIDER-SERVICE  # 匹配后提供服务的路由地址
         filters: #过滤器
           - AddRequestParameter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头加上一对请求头，名称为X-Request-Id 值为1024
         predicates:
           - Path=/payment/get/**  #断言，路径相匹配的进行路由
          # - After=2022-11-23T16:27:55.887+08:00[Asia/Shanghai]  #这个时间后访问才有效果 提前上线的利器
          # - Cookie=username,yyyzzz  #cookie中带有这个用户名才行 curl http://localhost:9527/payment/lb --cookie "username=yyyzzz"
          # - Header=X-Request-Id, \d+ # 请求头要有X-Request-Id属性,并且值为整数的正则表达式
          # - Host=**.zhangtao.com  #限定域名 -H "Host: com.zhangtao.com"
          #- Method=GET

       - id: payment_routh2
         #uri: http://localhost:8001
         uri: lb://CLOUD-PROVIDER-SERVICE  # 匹配后提供服务的路由地址
         predicates:
           - Path=/payment/lb/**
         #  - Cookie=username,yyyzzz  #cookie中带有这个用户名才行
         #  - Header=X-Request-Id,\d+ # 请求头要有X-Request-Id属性,并且值为整数的正则表达式

eureka:
  client:
    #表示自己注册进eurekaServer默认为true
    register-with-eureka: true
    fetchRegistry: true #是否从eureka抓取自己的注册信息，默认为true,单点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/  #单机版
      #defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/ #集群版
  instance:
    instanceId: cloudgateway9527 # 主机名称 eureka注册显示
    prefer-ip-address: true #显示主机IP
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒(默认90s),超时将剔除服务
    #lease-expiration-duration-in-seconds: 2
    #Eureka客户端向服务端发送心跳时间间隔，单位为秒(默认为30s)
    #lease-renewal-interval-in-seconds: 1