server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    #表示自己注册进eurekaServer默认为true
    register-with-eureka: false
    #fetchRegistry: true #是否从eureka抓取自己的注册信息，默认为true,丹姐点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
      #defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/ #集群版
#设置feign客户端超时时间（openfeign默认支持ribbon）
ribbon:
  ReadTimeout: 5000  #建立链接所需要的时间，适用于网络状况正常情况下,俩端连接所用的时间
  ConnectTimeout: 5000 #指的是建立连接后从服务器读取到可用资源所用时间

logging:
  level: # Feign日志以什么级别监控那个接口
    com.zhangtao.springcloud.service.PaymentFeignService: debug

feign:
  hystrix:
    enabled: true
